export const NAMESPACE = "EDITOR";

export const UPDATE_TEXT = `${NAMESPACE}/UPDATE_TEXT`;
export const UPDATE_FORMAT = `${NAMESPACE}/UPDATE_FORMAT`;
export const UPDATE_COLOR = `${NAMESPACE}/UPDATE_COLOR`;
export const REPLACE_WORD = `${NAMESPACE}/REPLACE_WORD`;
export const SET_SELECTION = `${NAMESPACE}/SET_SELECTION`;
export const CLEAR_SELECTION = `${NAMESPACE}/CLEAR_SELECTION`;
export const SET_SYNONYMS = `${NAMESPACE}/SET_SYNONYMS`;
